export const LITERALS = {
  shared: {
    loading: 'Cargando...',
    error: 'Ha ocurrido un error inesperado',
    errorLoad: 'Error al cargar los datos',
    errorLoadMessage: 'Comprueba tu conexión e inténtalo de nuevo',
    retry: 'Reintentar',
    confirm: 'Confirmar',
    cancel: 'Cancelar',
    save: 'Guardar',
    edit: 'Editar',
    delete: 'Eliminar',
    add: 'Añadir',
    back: 'Volver',
    search: 'Buscar',
    noResults: 'No se encontraron resultados',
    all: 'Todas',
    toastSuccess: 'Éxito',
    toastError: 'Error',
    toastInfo: 'Información',
  },

  auth: {
    loginTitle: 'Acceder',
    loginButton: 'Entrar',
    logoutButton: 'Cerrar sesión',
    emailLabel: 'Email',
    emailPlaceholder: 'correo@ejemplo.com',
    passwordLabel: 'Contraseña',
    passwordPlaceholder: '••••••••',
    logoutConfirm: '¿Seguro que quieres cerrar sesión?',
    loginSuccess: 'Sesión iniciada correctamente',
    loginError: 'Email o contraseña incorrectos',
    logoutSuccess: 'Sesión cerrada correctamente',
  },

  euros: {
    title: 'Monedas Euro',
    countriesTitle: 'Colección Euro',
    searchCountries: 'Buscar por país...',
    searchYears: 'Buscar por año...',
    searchCoins: 'Buscar por moneda...',
    back: 'Volver',
    regular: 'corrientes',
    commemorative: 'conmemorativas',
    emptySearch: 'No se encontraron resultados',
    filterAll: 'Todas',
    filterOwned: 'Obtenidas',
    filterMissing: 'Faltantes',
    filterCirculation: 'Circulación',
    filterCommemorative: 'Conmemorativas',
    colCountry: 'País',
    colYear: 'Año',
    colFaceValue: 'Valor',
    colMint: 'Ceca',
    colConservation: 'Estado',
    colUnits: 'Uds.',
    colCirculation: 'Circulación',
    addCoin: 'Añadir moneda',
    editCoin: 'Editar moneda',
    deleteCoin: 'Eliminar moneda',
    deleteConfirm: '¿Seguro que quieres eliminar esta moneda?',
    saveSuccess: 'Moneda guardada correctamente',
    saveError: 'Error al guardar la moneda',
    deleteSuccess: 'Moneda eliminada correctamente',
    deleteError: 'Error al eliminar la moneda',
    observationsLabel: 'Observaciones',
    observationsPlaceholder: 'Notas sobre esta moneda...',
    unitsLabel: 'Unidades',
    conservationLabel: 'Estado de conservación',
    noObservations: 'Sin observaciones',
    nonCirculatingLegend: 'Monedas sombreadas: no circulantes',
  },

  sidebar: {
    sectionLabel: 'Colecciones',
    numistaRemaining: 'Numista',
    logoAlt: 'coinsDDLP logo',
    euros: 'Euro',
    conmemorativas: 'Conmemorativas',
    pesetas: 'Peseta',
    ubicacion: 'Ubicación',
    estadisticas: 'Estadísticas',
  },

  coinDetail: {
    labelIssuer: 'Emisor',
    labelType: 'Tipo',
    labelYears: 'Años',
    labelComposition: 'Composición',
    labelWeight: 'Peso',
    labelDiameter: 'Diámetro',
    labelThickness: 'Grosor',
    labelShape: 'Forma',
    labelTechnique: 'Técnica',
    labelReferences: 'Referencias',
    labelObverse: 'Anverso',
    labelReverse: 'Reverso',
    labelFeatures: 'Características',
    labelObservations: 'Observaciones',
    labelNoObservations: 'Sin observaciones',
    labelMoreInfo: 'Más información en Numista',
    loadingNumista: 'Cargando datos de Numista...',
    errorNumista: 'No se pudieron cargar los datos de Numista',
  },

  conmemorativas: {
    title: 'Monedas Conmemorativas',
  },

  pesetas: {
    title: 'Colección Pesetas',
  },

  estadisticas: {
    title: 'Estadísticas',
    totalCoins: 'Total monedas',
    ownedCoins: 'Obtenidas',
    missingCoins: 'Faltantes',
    byCountry: 'Por país',
    byValue: 'Por valor facial',
  },

  ubicacion: {
    title: 'Ubicación',
  },
} as const;
