export const LITERALS = {
  shared: {
    loading: 'Cargando...',
    error: 'Ha ocurrido un error inesperado',
    errorLoad: 'Error al cargar los datos',
    errorLoadMessage: 'Comprueba tu conexión e inténtalo de nuevo',
    retry: 'Reintentar',
    confirm: 'Confirmar',
    cancel: 'Cancelar',
    save: 'Guardar',
    edit: 'Editar',
    delete: 'Eliminar',
    add: 'Añadir',
    back: 'Volver',
    search: 'Buscar',
    noResults: 'No se encontraron resultados',
    all: 'Todas',
    toastSuccess: 'Éxito',
    toastError: 'Error',
    toastInfo: 'Información',
  },

  auth: {
    loginTitle: 'Acceder',
    loginButton: 'Entrar',
    logoutButton: 'Cerrar sesión',
    emailLabel: 'Email',
    emailPlaceholder: 'correo@ejemplo.com',
    passwordLabel: 'Contraseña',
    passwordPlaceholder: '••••••••',
    logoutConfirm: '¿Seguro que quieres cerrar sesión?',
    loginSuccess: 'Sesión iniciada correctamente',
    loginError: 'Email o contraseña incorrectos',
    logoutSuccess: 'Sesión cerrada correctamente',
    forgotPassword: '¿Olvidaste tu contraseña?',
    forgotTitle: 'Restablecer contraseña',
    resetButton: 'Enviar enlace',
    resetSent: 'Te hemos enviado un enlace a tu email para restablecer la contraseña.',
    backToLogin: 'Volver al inicio de sesión',
    resetError: 'No se pudo enviar el email de restablecimiento',
    recoveryTitle: 'Nueva contraseña',
    newPasswordLabel: 'Nueva contraseña',
    newPasswordPlaceholder: '••••••••',
    confirmPasswordLabel: 'Confirmar contraseña',
    confirmPasswordPlaceholder: '••••••••',
    recoveryButton: 'Guardar contraseña',
    recoverySuccess: 'Contraseña actualizada correctamente',
    recoveryError: 'No se pudo actualizar la contraseña',
    passwordMismatch: 'Las contraseñas no coinciden',
  },

  euros: {
    title: 'Monedas Euro',
    countriesTitle: 'Colección Euro',
    searchCountries: 'Buscar por país...',
    searchYears: 'Buscar por año...',
    searchCoins: 'Buscar por moneda...',
    back: 'Volver',
    regular: 'corrientes',
    commemorative: 'conmemorativas',
    emptySearch: 'No se encontraron resultados',
    filterAll: 'Todas',
    filterOwned: 'Obtenidas',
    filterMissing: 'Faltantes',
    filterCirculation: 'Circulación',
    filterCommemorative: 'Conmemorativas',
    colCountry: 'País',
    colYear: 'Año',
    colFaceValue: 'Valor',
    colMint: 'Ceca',
    colConservation: 'Estado',
    colUnits: 'Uds.',
    colCirculation: 'Circulación',
    addCoin: 'Añadir moneda',
    editCoin: 'Editar moneda',
    deleteCoin: 'Eliminar moneda',
    deleteConfirm: '¿Seguro que quieres eliminar esta moneda?',
    saveSuccess: 'Moneda guardada correctamente',
    saveError: 'Error al guardar la moneda',
    deleteSuccess: 'Moneda eliminada correctamente',
    deleteError: 'Error al eliminar la moneda',
    observationsLabel: 'Observaciones',
    observationsPlaceholder: 'Notas sobre esta moneda...',
    unitsLabel: 'Unidades',
    conservationLabel: 'Estado de conservación',
    circulationLabel: 'Circulante',
    idNumLabel: 'ID Numista',
    descriptionLabel: 'Descripción',
    noObservations: 'Sin observaciones',
    nonCirculatingLegend: 'Monedas sombreadas: no circulantes',
  },

  sidebar: {
    sectionLabel: 'Colecciones',
    numistaRemaining: 'Numista',
    logoAlt: 'coinsDDLP logo',
    euros: 'Euro',
    conmemorativas: 'Conmemorativas',
    pesetas: 'Peseta',
    ubicacion: 'Ubicación',
    estadisticas: 'Estadísticas',
    admin: 'Administración',
    tools: 'Herramientas',
  },

  coinDetail: {
    labelIssuer: 'Emisor',
    labelType: 'Tipo',
    labelYears: 'Años',
    labelComposition: 'Composición',
    labelWeight: 'Peso',
    labelDiameter: 'Diámetro',
    labelThickness: 'Grosor',
    labelShape: 'Forma',
    labelTechnique: 'Técnica',
    labelReferences: 'Referencias',
    labelObverse: 'Anverso',
    labelReverse: 'Reverso',
    labelFeatures: 'Características',
    labelObservations: 'Observaciones',
    labelNoObservations: 'Sin observaciones',
    labelMoreInfo: 'Más información en Numista',
    loadingNumista: 'Cargando datos de Numista...',
    errorNumista: 'No se pudieron cargar los datos de Numista',
    labelNoImages: 'Imágenes no disponibles',
    labelBasicData: 'Datos básicos',
    labelYear: 'Año',
    labelCountry: 'País',
    labelFaceValue: 'Valor facial',
    labelDescription: 'Descripción',
    labelMint: 'Ceca',
    labelCirculation: 'Circulante',
    labelYes: 'Sí',
    labelNo: 'No',
  },

  admin: {
    title: 'Administración',
    navUsers: 'Usuarios',
    usersTitle: 'Gestión de usuarios',
    colEmail: 'Email',
    colName: 'Nombre',
    colRole: 'Rol',
    colActions: 'Acciones',
    newUser: 'Nuevo usuario',
    editUser: 'Editar usuario',
    deleteUser: 'Eliminar usuario',
    deleteConfirm: '¿Seguro que quieres eliminar este usuario?',
    roleAdmin: 'Admin',
    roleUser: 'Usuario',
    createTitle: 'Nuevo usuario',
    editTitle: 'Editar usuario',
    nameLabel: 'Nombre',
    namePlaceholder: 'Nombre completo',
    roleLabel: 'Rol',
    saveSuccess: 'Usuario guardado correctamente',
    saveError: 'Error al guardar el usuario',
    deleteSuccess: 'Usuario eliminado correctamente',
    deleteError: 'Error al eliminar el usuario',
  },

  herramientas: {
    title: 'Herramientas',
    navMonedas: 'Monedas',
    navAddEuro: 'Añadir moneda euro',
    monedasTitle: 'Catálogo de monedas',
    search: 'Buscar por valor, descripción o país...',
    editCoin: 'Editar datos del catálogo',
    colCountry: 'País',
    colYear: 'Año',
    colFaceValue: 'Valor',
    colDescription: 'Descripción',
    colCommemorative: 'Conm.',
    colIdNum: 'ID Numista',
    colActions: 'Acciones',
    labelCountry: 'País',
    labelYear: 'Año',
    labelFaceValue: 'Valor facial',
    labelDescription: 'Descripción',
    labelMint: 'Ceca',
    labelCommemorative: 'Conmemorativa',
    labelCirculation: 'Circulante',
    labelIdNum: 'ID Numista',
    labelUds: 'Unidades',
    labelConservation: 'Estado de conservación',
    labelObservations: 'Observaciones',
    observationsPlaceholder: 'Notas sobre esta moneda...',
    placeholderCountry: 'Selecciona un país',
    placeholderFaceValue: 'Selecciona valor facial',
    placeholderConservation: 'Selecciona estado',
    placeholderMint: 'Selecciona ceca',
    addButton: 'Añadir moneda',
    navAddYear: 'Añadir año',
    labelSourceYear: 'Año fuente',
    labelTargetYear: 'Año destino',
    placeholderSourceYear: 'Selecciona año fuente',
    tiradaButton: 'Añadir tirada',
    tiradaSuccess: 'monedas añadidas correctamente',
    tiradaError: 'Error al añadir la tirada',
    tiradaEmpty: 'No se encontraron monedas de circulación para ese año',
    saveSuccess: 'Moneda actualizada correctamente',
    saveError: 'Error al actualizar la moneda',
    addSuccess: 'Moneda añadida correctamente',
    addError: 'Error al añadir la moneda',
  },

  conmemorativas: {
    title: 'Conmemorativas',
    search: 'Buscar por país o descripción...',
    colCountry: 'País',
    colMint: 'Ceca',
    colDescription: 'Descripción',
    colLocation: 'Álb / H / Pos',
    colConservation: 'Estado',
    colUnits: 'Uds.',
    emptySearch: 'No se encontraron resultados',
  },

  pesetas: {
    title: 'Colección Pesetas',
    search: 'Buscar por valor o título...',
    colYear: 'Año',
    colTitle: 'Título',
    colMintage: 'Tirada',
    colConservation: 'Estado',
    colUnits: 'Uds.',
    emptySearch: 'No se encontraron resultados',
  },

  estadisticas: {
    title: 'Estadísticas',
    totalCoins: 'Total monedas',
    ownedCoins: 'Obtenidas',
    missingCoins: 'Faltantes',
    byCountry: 'Por país',
    byValue: 'Por valor facial',
  },

  ubicacion: {
    title: 'Ubicación',
  },
} as const;
