export const ALBUM_POSITIONS_PER_ROW   = 4;
export const ALBUM_ROWS_PER_PAGE       = 5;
export const ALBUM_POSITIONS_PER_PAGE  = ALBUM_ROWS_PER_PAGE * ALBUM_POSITIONS_PER_ROW; // 20
export const ALBUM_PAGES_PER_ALBUM     = 8;
export const ALBUM_POSITIONS_PER_ALBUM = ALBUM_POSITIONS_PER_PAGE * ALBUM_PAGES_PER_ALBUM; // 160
